### PR TITLE
Remove deprecated methods that operate on UriInfo

### PR DESCRIPTION
**Pull request by stevegutz**
This is a follow-up to https://github.com/HubSpot/httpQL/pull/5. See the internal issue for searches that show these are unused.

@nbelisle @boulter 
/cc @jhaber

### CODE REVIEW

**Comment by nbelisle11** [comment]
We should probably bump the version too, I think

**Comment by jhaber** [comment]
👍  will the jersey portion need to get split into a separate module?

**Comment by stevegutz** [comment]
@nbelisle It's always been on `1.0-SNAPSHOT` and has [never been published to maven central](https://search.maven.org/#search%7Cga%7C1%7Chttpql), so I'm not sure what a version change gets us.

@jhaber Yeah, that's listed on the internal repo.

**Comment by nbelisle11** [comment]
👍 Didn't realize it had never been published

**Pull request merged**
